/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Storygenerator } from "./Storygenerator";
import { StorygeneratorCountArgs } from "./StorygeneratorCountArgs";
import { StorygeneratorFindManyArgs } from "./StorygeneratorFindManyArgs";
import { StorygeneratorFindUniqueArgs } from "./StorygeneratorFindUniqueArgs";
import { DeleteStorygeneratorArgs } from "./DeleteStorygeneratorArgs";
import { StorygeneratorService } from "../storygenerator.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Storygenerator)
export class StorygeneratorResolverBase {
  constructor(
    protected readonly service: StorygeneratorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Storygenerator",
    action: "read",
    possession: "any",
  })
  async _storygeneratorsMeta(
    @graphql.Args() args: StorygeneratorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Storygenerator])
  @nestAccessControl.UseRoles({
    resource: "Storygenerator",
    action: "read",
    possession: "any",
  })
  async storygenerators(
    @graphql.Args() args: StorygeneratorFindManyArgs
  ): Promise<Storygenerator[]> {
    return this.service.storygenerators(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Storygenerator, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Storygenerator",
    action: "read",
    possession: "own",
  })
  async storygenerator(
    @graphql.Args() args: StorygeneratorFindUniqueArgs
  ): Promise<Storygenerator | null> {
    const result = await this.service.storygenerator(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Storygenerator)
  @nestAccessControl.UseRoles({
    resource: "Storygenerator",
    action: "delete",
    possession: "any",
  })
  async deleteStorygenerator(
    @graphql.Args() args: DeleteStorygeneratorArgs
  ): Promise<Storygenerator | null> {
    try {
      return await this.service.deleteStorygenerator(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
