/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { StorygeneratorService } from "../storygenerator.service";
import { StorygeneratorCreateInput } from "./StorygeneratorCreateInput";
import { StorygeneratorWhereInput } from "./StorygeneratorWhereInput";
import { StorygeneratorWhereUniqueInput } from "./StorygeneratorWhereUniqueInput";
import { StorygeneratorFindManyArgs } from "./StorygeneratorFindManyArgs";
import { StorygeneratorUpdateInput } from "./StorygeneratorUpdateInput";
import { Storygenerator } from "./Storygenerator";

export class StorygeneratorGrpcControllerBase {
  constructor(protected readonly service: StorygeneratorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Storygenerator })
  @GrpcMethod("StorygeneratorService", "createStorygenerator")
  async createStorygenerator(
    @common.Body() data: StorygeneratorCreateInput
  ): Promise<Storygenerator> {
    return await this.service.createStorygenerator({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Storygenerator] })
  @ApiNestedQuery(StorygeneratorFindManyArgs)
  @GrpcMethod("StorygeneratorService", "storygenerators")
  async storygenerators(
    @common.Req() request: Request
  ): Promise<Storygenerator[]> {
    const args = plainToClass(StorygeneratorFindManyArgs, request.query);
    return this.service.storygenerators({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Storygenerator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("StorygeneratorService", "storygenerator")
  async storygenerator(
    @common.Param() params: StorygeneratorWhereUniqueInput
  ): Promise<Storygenerator | null> {
    const result = await this.service.storygenerator({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Storygenerator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("StorygeneratorService", "updateStorygenerator")
  async updateStorygenerator(
    @common.Param() params: StorygeneratorWhereUniqueInput,
    @common.Body() data: StorygeneratorUpdateInput
  ): Promise<Storygenerator | null> {
    try {
      return await this.service.updateStorygenerator({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Storygenerator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("StorygeneratorService", "deleteStorygenerator")
  async deleteStorygenerator(
    @common.Param() params: StorygeneratorWhereUniqueInput
  ): Promise<Storygenerator | null> {
    try {
      return await this.service.deleteStorygenerator({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
